### ISSUE TITLE
How to centre the images? 

### ISSUE THREAD

**Issue by MariuzM** [eiriklv/react-masonry-component#151]
I know this is lame should be a simple CSS but can't seem to get it working.
![Screenshot 2020-04-17 at 16 32 35](https://user-images.githubusercontent.com/36937039/79586893-abf58e80-80c9-11ea-88cb-3f7b9253868c.png)
Where the blue background is it's just empty space i want the images to be centered 

```js
<div className="grid">
  <Masonry
    className="portfolio-main"
    elementType="div"
    options={masonryOptions}
    disableImagesLoaded={false}
    updateOnEachImageLoad={false}
  >
    {state.map((el) => {
      // console.log(el)
      return (
        // <a href={`img/${page}/${el}`}>
        <img src={`img/${page}/${el}`} className="grid-item" alt="" width="200px" />
        // </a>
      )
    })}
  </Masonry>
</div>
```

css - what i have tried
```css
.portfolio-main {
  display: flex;
  align-items: center;
  justify-content: center;
  align-content: center;
  background-color: rgba(0, 0, 255, 0.123);
}
```
